Import('os_env')

sources = [
    'entry.S',
    'kernel.c',
    'uart.c',
    'page.c',
    'printf.c',
    'app.S',
    'sched.c',
    'switch.S',
    'trap.S',
    'trap.c',
    'plic.c'
]

objects = []

for src in sources:
    obj = '%s.o' % (src)
    objects.append(os_env.Object(target=obj, source=src))

Return('objects', stop=True)
